--- #YAML:1.0
name:                Text-WikiCreole
version:             0.05
abstract:            Convert Wiki Creole 1.0 markup to XHTML
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Jason Burnett <jason@jnj.org>
